# -*- coding: utf-8 -*-
"""nucleotide_composition.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-Kj5HnAQkvVdSMMaCTEPm7Y-bkjgC_T
"""

# set the name of input DNA sequence file
filename = 'dna.txt'

# open the input file
infile = open(filename, 'r')

# print(infile)

#read the file
dna_sequence = infile.read().rstrip()
#dna_sequence = dna_sequence.rstrip()

# print the dna sequence
print(dna_sequence)


# close the file
infile.close()

print(dna_sequence)

seqlen = len(dna_sequence)
print('Sequence Length', seqlen)

numA = dna_sequence.count('A')
freqA = numA/seqlen
print("Freq of A", ":", freqA)

numC = dna_sequence.count('C')
freqC = numC/seqlen
print("Freq of C", ":", freqC)

numG = dna_sequence.count('G')
freqG = numG/seqlen
print("Freq of G", ":", freqG)

numT = dna_sequence.count('T')
freqT = numT/seqlen
print("Freq of T", ":", freqT)

freqG_C = (numG + numC)/seqlen
print("G+C content", ":", freqG_C)

print(freqA + freqC + freqG + freqT)

outfile = open('my_first_output.txt ', 'w')
outfile.write('DNA sequence: ' + dna_sequence + '\n')
outfile.write('Sequence length ' + str(seqlen) + 'nt' + '\n')
outfile.write("Freq of A: " + str(freqA) + '\n')
outfile.write("Freq of G: " + str(freqG) + '\n')
outfile.write("Freq of C: " + str(freqC) + '\n')
outfile.write("Freq of T: " + str(freqT) + '\n')
outfile.write("G+C content: " + str(freqG_C) + '\n')

from google.colab import files
uploaded = files.upload()