# -*- coding: utf-8 -*-
"""write_razor_pbs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v6CgFgpxbcszWXYoO4ThqEIKZ0kUK1UT
"""

#! /usr/bin/env python3

# This script generates a PBS file for the AHPCC Razor cluster

# Define some variables
job = 'razor_04.1.pbs'
queue = 'onenode16core'
prefix = 'razor_04.1.out$PBS_JOBID'
nodes = 1 
ppn = 1
wall = 3 # this is in hours

# This section prints the header/required info for the PBS script
print('PBS -N', job) # job name
print('PBS -q', queue) # which queue to use
print('PBS -j oe') # join the STDOUT and STDERR into single file
print('PBS -o', prefix) # set the name of the job output file
print('PBS -l', 'nodes=',nodes, 'ppn=',ppn) # how many resource to ask for (nodes = nun nodes, ppn = nun processors)
print('PBS -l walltime=' + str(wall) + ':00:00') # set the walltime (default is 1 hr)
print()

# cd into working directory
print('cd $PBS_O_WORKDIR')
print()

# load necessary modules
print('# load modules')
print('module purge')
print('module load gcc/7.2.1 python/3.6.0-anaconda java/sunjdk_1.8.0 blast mafft/7.304b')
print()

# commands for this job
print('# insert commands here')

